language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update --no-interaction

install:
  - composer install --no-interaction

before_script: mkdir -p build/logs

script: vendor/bin/phpunit

after_script: if [ $(phpenv version-name) = "5.6" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
